# Homebrew formula for gsigmad
# Tap: biobitworks/gsigmad
# Install: brew install biobitworks/gsigmad/gsigmad
#
# IMPORTANT: Before publishing, update:
# 1. url and sha256 with actual PyPI release values
# 2. Resource stanzas generated by: pip install homebrew-pypi-poet && poet gsigmad
# 3. Test with: brew audit --new-formula gsigmad && brew test gsigmad

class Gsigmad < Formula
  include Language::Python::Virtualenv

  desc "Science governance CLI -- deterministic guardrails for probabilistic AI"
  homepage "https://github.com/biobitworks/gettingsciencedone"
  # TODO: Replace with actual PyPI release URL and sha256 after publishing
  url "https://files.pythonhosted.org/packages/source/g/gsigmad/gsigmad-1.1.0.tar.gz"
  sha256 "PLACEHOLDER_SHA256"
  license "Apache-2.0"

  depends_on "python@3.11"

  # Resource stanzas for transitive dependencies.
  # Generate with: pip install homebrew-pypi-poet && poet gsigmad
  # Each resource block pins a specific version with sha256 checksum.
  #
  # Core dependencies from pyproject.toml:
  #   statsmodels>=0.14.5, scipy>=1.16.3, pyyaml>=6.0, pydantic>=2.12.4,
  #   rfc8785>=0.1.4, requests, tiktoken>=0.12, rich>=13.0, typer>=0.12,
  #   python-dateutil>=2.9

  # TODO: Run `poet gsigmad` and paste resource stanzas here.
  # Example:
  # resource "typer" do
  #   url "https://files.pythonhosted.org/packages/.../typer-0.24.1.tar.gz"
  #   sha256 "..."
  # end

  def install
    virtualenv_install_with_resources
  end

  test do
    system bin/"gsigmad", "--version"
    # Verify init creates the expected directory structure
    system bin/"gsigmad", "init", testpath/"test-project"
    assert_predicate testpath/"test-project"/".gsigmad"/"config.yaml", :exist?
  end
end
